### ISSUE TITLE
Node V10 is not supported due to `.flat()`

### ISSUE THREAD

**Issue by highvoltag3** [ajaymathur/w-project#2]
The following error is thrown using Node V10.
```
TypeError: (intermediate value).flat is not a function
    at Object.<anonymous> (/Users/{username}/node_modules/w-project/dist/commands/open.js:39:24)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/{username}/node_modules/w-project/dist/commands/open.js:5:58)
```

**Comment by highvoltag3** [comment]
Feel free to decline if just saying "node v12" is required in the README seems sufficient.
